from ..gmm_with_weighting import (weight_matrix, gen_moms_sse, gen_params,
                                  fit_one, weight_array, weight_matrix)
import numpy as np
import pandas as pd


class test_gmm_weighting(object):
    """
    Test data generated by

    In [4]: ctry = '001'

    In [5]: df = gmm.select('ctry_' + ctry)

    In [6]: import random

    In [7]: random.seed(42)

    In [8]: rows = random.sample(df.index, 1000)

    In [9]: sample = df.ix[rows]

    In [11]: sample.to_csv('/Users/tom/TradeData/data-wrangling/new_start/'
                           'tests/sample_data.csv')
    """
    def __init__(self):
        self.data = pd.read_csv('sample_data.csv')
    
