country_code = {
            '001': 'France',
            '002': 'Belg.-Luxbg',
            '003': 'Netherlands',
            '004': 'Fr Germany',
            '005': 'Italy',
            '006': 'Utd. Kingdom',
            '007': 'Ireland',
            '008': 'Denmark',
            '009': 'Greece',
            '010': 'Portugal',
            '011': 'Spain',
            '017': 'Belgium',
            '018': 'Luxembourg',
            '030': 'Sweden',
            '032': 'Finland',
            '038': 'Austria',
            '600': 'Cyprus',
            '061': 'Czech Republic',
            '053': 'Estonia',
            '064': 'Hungary',
            '055': 'Lithuania',
            '054': 'Latvia',
            '046': 'Malta',
            '060': 'Poland',
            '091': 'Slovenia',
            '063': 'Slovakia',
            '068': 'Bulgaria',
            '066': 'Romania',
            'EU': 'EU',
}

country_abbv = {
            '001': 'FR',
            # '002': 'Belg.-Luxbg',
            '003': 'NL',
            '004': 'DE',
            '005': 'IT',
            '006': 'UK',
            '007': 'IE',
            # '008': 'Denmark',
            # '009': 'Greece',
            '010': 'PT',
            '011': 'ES',
            '017': 'BE',
            # '018': 'Luxembourg',
            '030': 'SE',
            '032': 'FI',
            '038': 'AT',
            # '600': 'Cyprus',
            '061': 'CZ',
            '053': 'EE',
            '064': 'HU',
            '055': 'LT',
            # '054': 'Latvia',
            # '046': 'Malta',
            # '060': 'Poland',
            '091': 'SI',
            '063': 'SK',
            # '068': 'Bulgaria',
            '066': 'RO',
            # 'EU': 'EU',
}
